story/s1/urls.py
from django.urls import path, include
from . import views

app_name = 's1'

urlpatterns = [
    path('story-1', views.story1, name='story1'),
]

story/s3/urls.py
from django.urls import path, include
from . import views

app_name = 's3'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('achievements', views.achievements, name='achievements'),
    path('experience', views.experience, name='experience'),
    path('contacts', views.contacts, name='contacts'),
    path('challenge', views.challenge, name='challenge'),
    path('time', views.time, name='time'),
    path('time/<str:timezone>', views.time)
]

story/story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('s1.urls')),
    path('', include('s3.urls')),
]

story/s1/models.py
from django.db import models

# Create your models here.

story/s3/models.py
from django.db import models

# Create your models here.

story/s1/views.py
from django.shortcuts import render

# Create your views here.
def story1(request):
    return render(request, 's1/story1.html')

story/s3/views.py
from django.shortcuts import render
import datetime

# Create your views here.
def homepage(request):
    return render(request, 's3/homepage.html')

def achievements(request):
    return render(request, 's3/achievements.html')

def experience(request):
    return render(request, 's3/experience.html')

def contacts(request):
    return render(request, 's3/contacts.html')

def challenge(request):
    return render(request, 's3/Challenge3.html')

def time(request, timezone="0"):
    time = datetime.datetime.now() + datetime.timedelta(hours=int(timezone))
    return render(request, 's3/time.html', {'time':time})

story/s1/templates/s1/story1.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Story 1 by Syabib Ash-Shiddiqi</title>
        <link href="{% static 's1/css/style.css' %}" type="text/css" rel="stylesheet">
    </head>

    <body>
        <h1 class="navigation-bar">My Profile</h1>
        <div class="head">
            <center><img src="{% static 's1/images/picture.jpg' %}" alt="Foto Syabib di Jembatan Teksas" width="300" height="300" class="image-round">
            <h2 class="h2-slide-down">Halo semua!</h2>
            <p class="opening">
                Perkenalkan, nama saya Syabib. Saya adalah seorang mahasiswa ilmu komputer tahun pertama yang
                sangat ambisius, bersemangat, optimistis, dan memiliki memiliki keinginan yang besar untuk
                terus belajar dan berkembang dalam segala hal.<br>Ayo berkenalan dengan saya!
            </p>
            </center>
        </div>
        <div class="row">
            <div class="data">
                <h2>My Data</h2>
                <table>
                    <tr>
                        <td>Nama</td>
                        <td>:</td>
                        <td>Syabib Ash-Shiddiqi</td>
                    </tr>
                    <tr>
                        <td>NPM</td>
                        <td>:</td>
                        <td>1906350686</td>
                    </tr>
                    <tr>
                        <td>Angkatan</td>
                        <td>:</td>
                        <td>Maung 2019</td>
                    </tr>
                    <tr>
                        <td>Tempat Kuliah</td>
                        <td>:</td>
                        <td>Ilmu Komputer - Fasilkom UI</td>
                    </tr>
                    <tr class="table-slide-up">
                        <td>Riwayat Pendidikan</td>
                        <td>:</td>
                        <td>
                            <table>
                                <tr>
                                    <td>SDIT Adzkia</td>
                                    <td class="table-slide-more">2007 - 2013</td>
                                </tr>
                                <tr>
                                    <td>SMPN 8 Padang</td>
                                    <td class="table-slide-more">2013 - 2016</td>
                                </tr>                            <tr>
                                    <td>SMAN 1 Padang</td>
                                    <td class="table-slide-more">2016 - 2019</td>
                                </tr>
                                <tr>
                                    <td>Universitas Indonesia</td>
                                    <td class="table-slide-more">2019 - sekarang</td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td>Hobi</td>
                        <td>:</td>
                        <td>Bermain game dan menonton bola
                    </tr>
                </table>
            </div>
            <div class="contact">
                <h2>Contact me at</h2>
                <table>
                    <tbody>
                        <tr>
                            <td>
                                <img src="{% static 's1/images/gmail logo.png' %}" alt="gmail" height="27">
                            </td>
                            <td class="table-slide-left">syabib.ashshiddiqi@gmail.com</td>
                        </tr>
                        <tr>
                            <td>
                                <a href="https://www.linkedin.com/in/syabib-ash-shiddiqi-b4b031194/">
                                <img src="{% static 's1/images/gmail logo.png' %}" alt="linkedin" height="35" width="35">
                            </td>
                            <td class="table-slide-left">Syabib Ash-Shiddiqi</td class="table-slide-left">
                        </tr>
                        <tr>
                            <td>
                                <img src="{% static 's1/images/line logo.png' %}" alt="line" height="35" width="35">
                            </td>
                            <td class="table-slide-left">syabib_as_fone2</td class="table-slide-left">
                        </tr>
                        <tr>
                            <td>
                                <a href="https://www.instagram.com/syabib.a/">
                                <img src="{% static 's1/images/instagram logo.png' %}" alt="instagram" width="35" height="35">
                            </td>
                            <td class="table-slide-left">@syabib.a</td>
                        </tr>
                        <tr>
                            <td>
                                <a href="https://twitter.com/sasfort_">
                                <img src="{% static 's1/images/twitter logo.png' %}" alt="twitter" height="35" width="35">                            </td>
                            <td class="table-slide-left">@sasfort_</td class="table-slide-left">
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="footer">
            <center>
                by Syabib Ash-Shiddiqi, 2020
            </center>
        </div>
    </body>
</html>

story/s3/templates/s3/Challenge3.html
{% extends "s3/base.html" %}
{% load static %}
{% block body %}
<div class="container">
  <h2 class="turun-dikit">Galeri</h2>
    <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Buka Galeri</button>

    <div class="modal fade" id="myModal" role="dialog">
      <div class="modal-dialog">
      
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Galeri</h4>
          </div>
          <div class="modal-body">
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
              <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
              </ol>
              <div class="carousel-inner">
                <div class="item active">
                  <img src="{% static 's3/images/front.jpg' %}" alt="Los Angeles" style="width:100%;">
                  <div class="carousel-caption">
                    <h3>Salam Angkatan Terakhir</h3>
                    <p>Momen Kekerabatan</p>
                  </div>
                </div>
                <div class="item">
                  <img src="{% static 's3/images/mk.jpg' %}" alt="Chicago" style="width:100%;">
                  <div class="carousel-caption">
                    <h3>Terima Kasih, Maung!</h3>
                    <p>Cilodong, 24 November 2019</p>
                  </div>
                </div>
                <div class="item">
                  <img src="{% static 's3/images/cina.jpg' %}" alt="New York" style="width:100%;">
                  <div class="carousel-caption">
                    <h3>Cina</h3>
                    <p>Otw menguasai dunia</p>
                  </div>
                </div>
                <div class="item">
                  <img src="{% static 's3/images/kudeta.jpg' %}" alt="New York" style="width:100%;">
                  <div class="carousel-caption">
                    <h3>Kudeta</h3>
                    <p>Kuliah Demot Tapi Cum Laude</p>
                  </div>
                </div>
                <div class="item">
                  <img src="{% static 's3/images/meem.jpg' %}" alt="New York" style="width:100%;">
                </div>
              </div>
              <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="right carousel-control" href="#myCarousel" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
          </div>
      </div>
      
    </div>
  </div>
  
</div>
{% endblock %}

story/s3/templates/s3/achievements.html
{% extends "s3/base.html" %}
{% load static %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-3"><center>
            <table>
                <tr>
                    <img src="{% static 's3/images/picture.jpg' %}" alt="Foto Syabib di Jembatan Teksas" width="100%" height="100%" class="image-round">
                </tr>
                <tr>
                    <h4>Syabib Ash-Shiddiqi<br>18 tahun</h4>
                </tr>
            </table>
            </center></div>
            <div class="col-9">
                    <div class="main">
                    <div class="vertical-line"></div>
                    <h3>Prestasi</h3>
                    <div class="main-top-left-achievements">
                        <ol>
                            <li>Finalis Olimpidae Sains Nasional bidang Komputer 2018</li>
                            <li>Juara 1 ISCE Universitas Andalas tahun 2018</li>
                            <li>Juara 1 TENSAI bidang Komputer tahun 2018</li>
                            <li>Juara 1 Luminosity bidang Komputer tahun 2018</li>
                            <li>Harapan 2 SMAPSiC bidang Komputer tahun 2018</li>
                        </ol>
                    </div>
                    <div class="main-low-right-achievements">
                        <ol start="6">
                            <li>Semi-finalis National Logic Competition ITS tahun 2017</li>
                            <li>Finalis Olimpiade Sains Provinsi</li>
                            <li>Juara 3 SMAPSiC bidang Komputer tahun 2017</li>
                            <li>Harapan 1 TENSAI bidang Komputer tahun 2017</li>
                            <li>Juara 1 Lomba Band antar SMP se-Kota Padang tahun 2015</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

story/s3/templates/s3/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Esteban&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <link href="{% static 's3/css/style.css' %}" type="text/css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <script src="https://code.iconify.design/1/1.0.4/iconify.min.js"></script>
    <title>Base</title>
</head>
<body>
    {% include 's3/includes/navbar.html' %}
    {% block body %} {% endblock %}
</body>
</html>

story/s3/templates/s3/contacts.html
{% extends "s3/base.html" %}
{% load static %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-3"><center>
            <table>
                <tr>
                    <img src="{% static 's3/images/picture.jpg' %}" alt="Foto Syabib di Jembatan Teksas" width="100%" height="100%" class="image-round">
                </tr>
                <tr>
                    <h4>Syabib Ash-Shiddiqi<br>18 tahun</h4>
                </tr>
            </table>
            </center></div>
            <div class="col-9">
                    <div class="main">
                    <div class="vertical-line"></div>
                    <div class="main-top-left-achievements">
                        <h4>Contact me at:</h4>
                        <table>
                            <tbody>
                                <tr>
                                    <td>
                                        <img src="{% static 's3/images/gmail logo.png' %}" alt="gmail" height="27">
                                    </td>
                                    <td class="table-slide-left">syabib.ashshiddiqi@gmail.com</td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://www.linkedin.com/in/syabib-ash-shiddiqi-b4b031194/">
                                        <img src="{% static 's3/images/linkedin logo.png' %}" alt="linkedin" height="35" width="35">
                                    </td>
                                    <td class="table-slide-left">Syabib Ash-Shiddiqi</td class="table-slide-left">
                                </tr>
                                <tr>
                                    <td>
                                        <img src="{% static 's3/images/line logo.png' %}" alt="line" height="35" width="35">
                                    </td>
                                    <td class="table-slide-left">syabib_as_fone2</td class="table-slide-left">
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://www.instagram.com/syabib.a/">
                                        <img src="{% static 's3/images/instagram logo.png' %}" alt="instagram" width="35" height="35">
                                    </td>
                                    <td class="table-slide-left">@syabib.a</td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://twitter.com/sasfort_">
                                        <img src="{% static 's3/images/twitter logo.png' %}" alt="twitter" height="35" width="35">                            </td>
                                    <td class="table-slide-left">@sasfort_</td class="table-slide-left">
                                </tr>
                            </tbody>
                        </table>
                    </div>

                    <div class="challenge3">
                        <a href="{% url 's3:challenge' %}">
                       <b>PRESS FOR CHALLENGE 3</b>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

story/s3/templates/s3/experience.html
{% extends "s3/base.html" %}
{% load static %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-3"><center>
            <table>
                <tr>
                    <img src="{% static 's3/images/picture.jpg' %}" alt="Foto Syabib di Jembatan Teksas" width="100%" height="100%" class="image-round">
                </tr>
                <tr>
                    <h4>Syabib Ash-Shiddiqi<br>18 tahun</h4>
                </tr>
            </table>
            </center></div>
            <div class="col-9">
                    <div class="main">
                    <div class="vertical-line"></div>
                    <div class="main-top-left-achievements">
                        <h4>Organisasi</h4>
                        <table>
                            <tr>
                                <td>1. Taring Maung</td>
                                <td>2019 - sekarang</td>
                            </tr>
                            <tr>
                                <td>2. Akademis Maung</td>
                                <td>2019 - sekarang</td>
                            </tr>
                            <tr>
                                <td>3. Humas Maung</td>
                                <td>2019 - sekarang</td>
                            </tr>
                            <tr>
                                <td>4. DPH Rohis SMAN 1 Padang</td>
                                <td>2017 - 2019</td>
                            </tr>
                        </table>
                    </div>
                    <div class="main-low-right-achievements">
                        <h4 class="geser">Kepanitiaan</h4>
                        <ol>
                            <li>1. Staff Field Coordinator PERAK 2020</li>
                            <li>2. Koordinator Mentor Social Project Maung #2</li>
                            <li>3. Koordinator Tempat Wisuda Tahfizh 5 SMAN 1 Padang</li>
                            <li>4. Staff Perlengkapan SMAPSiC XIII + Jr IX</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

story/s3/templates/s3/homepage.html
{% extends "s3/base.html" %}
{% load static %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-3"><center>
            <table>
                <tr>
                    <img src="{% static 's3/images/picture.jpg' %}" alt="Foto Syabib di Jembatan Teksas" width="100%" height="100%" class="image-round">
                </tr>
                <tr>
                    <h4>Syabib Ash-Shiddiqi<br>18 tahun</h4>
                </tr>
            </table>
            </center></div>
            <div class="col-9">
                <div class="main">
                <div class="vertical-line"></div>
                <h3>Profil</h3>
                <table>
                    <tbody>
                        <tr>
                            <th>Nama</th>
                            <td>:</td>
                            <td>Syabib Ash-Shiddiqi</td>
                        </tr>
                        <tr>
                            <th>NPM</th>
                            <td>:</td>
                            <td>1906350686</td>
                        </tr>
                        <tr>
                            <th>Angkatan</th>
                            <td>:</td>
                            <td>Maung 2019</td>
                        </tr>
                        <tr>
                            <th>Hobi</th>
                            <td>:</td>
                            <td>Bermain video game dan menonton bola</td>
                        </tr>
                        <tr>
                            <th>Tempat Kuliah</th>
                            <td>:</td>
                            <td>Ilmu Komputer UI</td>
                        </tr>
                        <tr>
                            <th valign="top">Riwayat Pendidikan</th>
                            <td valign="top">:</td>
                            <td>
                                <table>
                                    <tr>
                                        <td>SDIT Adzkia</td>
                                        <td>2007 - 2013</td>
                                    </tr>
                                    <tr>
                                        <td>SMPN 8 Padang</td>
                                        <td>2013 - 2016</td>
                                    </tr>
                                    <tr>
                                        <td>SMAN 1 Padang</td>
                                        <td>2016 - 2019</td>
                                    </tr>
                                    <tr>
                                        <td>Universitas Indonesia</td>
                                        <td>2019 - sekarang</td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <div class="main-low-right-homepage">
                    <p>Seorang mahasiswa ilmu komputer tahun pertama yang sangat bersemangat, ambisius, optimistis, 
                        dan memiliki keinginan yang sangat besar untuk terus belajar dan berkembang di segala hal.</p>
                </div>
            </div>
            </div>
        </div>
    </div>
{% endblock %}

story/s3/templates/s3/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 's3:homepage' %}">Homepage</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 's3:achievements' %}">Achievements</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 's3:experience' %}">Experience</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 's3:contacts' %}">Contacts</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 's3:challenge' %}">Challenge 3</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 's1:story1' %}">Story 1</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 's3:time' %}">Time</a>
      </li>
    </ul>
  </div>
</nav>

story/s3/templates/s3/time.html
{% extends "s3/base.html" %}
{% load static %}
{% block body %}
{{ time }}
{% endblock %}